### ISSUE TITLE
GitHub API credentials are expired (probably)

### ISSUE THREAD

**Issue by Hirse** [SAP/sap.github.com#10]
The requests to the GitHub API all return with a 401:

> {
>   "message": "Bad credentials",
>   "documentation_url": "https://developer.github.com/v3"
> }

**Comment by larshp** [comment]
same problem today

**Comment by larshp** [comment]
this is still an issue

**Comment by jonathanbaker7** [comment]
What are you trying to do on the API, and what credentials are you using?

**Comment by larshp** [comment]
trying to access http://sap.github.com  notice the null values shown on the page, and switch on developer tootls to see what happens

**Comment by jonathanbaker7** [comment]
This page is so far out of date that we may take it down.  I'll get some feedback from the management team, and respond in a few days.

**Comment by larshp** [comment]
Note that:
"For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the user making requests."
https://developer.github.com/v3/

**Comment by jonathanbaker7** [comment]
We replaced the old page with a new page, which uses the un-authenticated API.  This API will have a rate limitation (which makes sense, since it is public).  If you don't reload the page more than 20 times per hour, this should not be an issue.

There is a separate work stream to create a new dynamically-built page using a dedicated server.  When this project moves to beta, we will announce it to this group.
