### ISSUE TITLE
Sort by newest : By clicking on icon and using the URL giving different result

### ISSUE THREAD

**Issue by tapasweni-pathak** [SAP/sap.github.com#9]
1. Go to all projects.
2. Click on the fa icon clock to get the project list sorted, newest first.
3. Use the URL http://sap.github.io/index.html?sort=newest&filter=all to get the project list sorted, newest first.

The results given by step 2 and 3 are different.

**Comment by jonathanbaker7** [comment]
There were a few sorting bugs in the code, and they were fixed in a minor revision a few months ago.  I just checked, and both now appear to show the same thing.  I expect the bug fixes also resolved this issue.

I'll mark this as closed, but if you see the problem again, please let me know immediately.  Thanks!
